USE [master]
GO

/****** Object:  Database [ConsommationDW]    Script Date: 07/11/2018 16:11:00 ******/
CREATE DATABASE [ConsommationDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ConsommationDW', FILENAME = N'E:\INSA Informatique\4eme annee\Base de donnee decisionnelle\tp2\data\ConsommationDW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ConsommationDW_log', FILENAME = N'E:\INSA Informatique\4eme annee\Base de donnee decisionnelle\tp2\data\ConsommationDW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ConsommationDW] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ConsommationDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ConsommationDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ConsommationDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ConsommationDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ConsommationDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ConsommationDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [ConsommationDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ConsommationDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ConsommationDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ConsommationDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ConsommationDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ConsommationDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ConsommationDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ConsommationDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ConsommationDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ConsommationDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ConsommationDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ConsommationDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ConsommationDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ConsommationDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ConsommationDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ConsommationDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ConsommationDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ConsommationDW] SET RECOVERY FULL 
GO

ALTER DATABASE [ConsommationDW] SET  MULTI_USER 
GO

ALTER DATABASE [ConsommationDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ConsommationDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ConsommationDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ConsommationDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ConsommationDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ConsommationDW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ConsommationDW] SET  READ_WRITE 
GO

